/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActivityDetail } from '../model/models';
import { ActivityPage } from '../model/models';
import { ErrorResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ActivitiesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get activity detail including computed ride metrics
     * 
     * @endpoint get /api/activities/{id}
     * @param id 
     */
    getActivity(id: number, extraHttpRequestParams?: any): Observable<ActivityDetail>;

    /**
     * List all activities
     * 
     * @endpoint get /api/activities
     * @param page 
     * @param size 
     */
    listActivities(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ActivityPage>;

}
