export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './activities.serviceInterface';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './calendar.serviceInterface';
export * from './coaching.service';
import { CoachingService } from './coaching.service';
export * from './coaching.serviceInterface';
export * from './ftp.service';
import { FtpService } from './ftp.service';
export * from './ftp.serviceInterface';
export * from './nutrition.service';
import { NutritionService } from './nutrition.service';
export * from './nutrition.serviceInterface';
export * from './pmc.service';
import { PmcService } from './pmc.service';
export * from './pmc.serviceInterface';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './settings.serviceInterface';
export * from './sync.service';
import { SyncService } from './sync.service';
export * from './sync.serviceInterface';
export * from './training.service';
import { TrainingService } from './training.service';
export * from './training.serviceInterface';
export const APIS = [ActivitiesService, CalendarService, CoachingService, FtpService, NutritionService, PmcService, SettingsService, SyncService, TrainingService];
