/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CalendarResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CalendarServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get calendar data for a month
     * 
     * @endpoint get /api/calendar
     * @param year 
     * @param month 
     */
    getCalendar(year: number, month: number, extraHttpRequestParams?: any): Observable<CalendarResponse>;

}
