/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CoachingRequest } from '../model/models';
import { CoachingResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CoachingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Request on-demand AI analysis for a ride
     * 
     * @endpoint post /api/coaching/analyze
     * @param coachingRequest 
     */
    analyzeRide(coachingRequest: CoachingRequest, extraHttpRequestParams?: any): Observable<CoachingResponse>;

}
