/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FtpEntry } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FtpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get FTP history (auto-detected and estimated entries)
     * 
     * @endpoint get /api/ftp
     */
    getFtpHistory(extraHttpRequestParams?: any): Observable<Array<FtpEntry>>;

}
