/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { NutritionPlan } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NutritionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Generate AI nutrition plan for a completed ride
     * 
     * @endpoint post /api/nutrition/generate/ride/{id}
     * @param id 
     */
    generateNutritionForRide(id: number, extraHttpRequestParams?: any): Observable<NutritionPlan>;

    /**
     * Generate AI nutrition plan for a planned workout
     * 
     * @endpoint post /api/nutrition/generate/workout/{id}
     * @param id 
     */
    generateNutritionForWorkout(id: number, extraHttpRequestParams?: any): Observable<NutritionPlan>;

    /**
     * Get persisted nutrition plan for a completed ride
     * 
     * @endpoint get /api/nutrition/ride/{id}
     * @param id 
     */
    getNutritionForRide(id: number, extraHttpRequestParams?: any): Observable<NutritionPlan>;

    /**
     * Get persisted nutrition plan for a planned workout
     * 
     * @endpoint get /api/nutrition/workout/{id}
     * @param id 
     */
    getNutritionForWorkout(id: number, extraHttpRequestParams?: any): Observable<NutritionPlan>;

}
