/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PmcDataPoint } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PmcServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get CTL/ATL/TSB time series for the Performance Management Chart
     * 
     * @endpoint get /api/pmc
     * @param from 
     * @param to 
     */
    getPmc(from?: string, to?: string, extraHttpRequestParams?: any): Observable<Array<PmcDataPoint>>;

}
