/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppSettings } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SettingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get current app settings (read-only, from application.yml)
     * 
     * @endpoint get /api/settings
     */
    getSettings(extraHttpRequestParams?: any): Observable<AppSettings>;

}
