/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { GarminAuthRequest } from '../model/models';
import { SyncStatus } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SyncServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Authenticate with Garmin SSO (credentials used in-memory only)
     * 
     * @endpoint post /api/sync/authenticate
     * @param garminAuthRequest 
     */
    authenticate(garminAuthRequest: GarminAuthRequest, extraHttpRequestParams?: any): Observable<SyncStatus>;

    /**
     * Get current sync status and session validity
     * 
     * @endpoint get /api/sync/status
     */
    getSyncStatus(extraHttpRequestParams?: any): Observable<SyncStatus>;

    /**
     * Trigger a manual Garmin activity sync
     * 
     * @endpoint post /api/sync/trigger
     */
    triggerSync(extraHttpRequestParams?: any): Observable<SyncStatus>;

}
