/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { GoalEvent } from '../model/models';
import { GoalEventRequest } from '../model/models';
import { TrainingPlan } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TrainingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new goal event (deactivates any existing active goal)
     * 
     * @endpoint post /api/goal
     * @param goalEventRequest 
     */
    createGoal(goalEventRequest: GoalEventRequest, extraHttpRequestParams?: any): Observable<GoalEvent>;

    /**
     * Download ZWO file for a planned workout (Zwift import)
     * 
     * @endpoint get /api/training-plan/workouts/{id}/zwo
     * @param id 
     */
    downloadZwo(id: number, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Trigger AI training plan generation for the active goal
     * 
     * @endpoint post /api/training-plan/generate
     */
    generateTrainingPlan(extraHttpRequestParams?: any): Observable<TrainingPlan>;

    /**
     * Get the current active goal event
     * 
     * @endpoint get /api/goal
     */
    getActiveGoal(extraHttpRequestParams?: any): Observable<GoalEvent>;

    /**
     * Get the current AI-generated training plan with weeks and workouts
     * 
     * @endpoint get /api/training-plan
     */
    getTrainingPlan(extraHttpRequestParams?: any): Observable<TrainingPlan>;

}
