/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivitySummary { 
    id?: number;
    name?: string;
    startTime?: string;
    date?: string;
    distanceKm?: number;
    durationSeconds?: number;
    elevationGainM?: number;
    avgPowerW?: number;
    normalizedPowerW?: number;
    tss?: number;
    intensityFactor?: number;
}

