/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivitySummary } from './activitySummary';


export interface ActivityPage { 
    content?: Array<ActivitySummary>;
    totalElements?: number;
    page?: number;
    size?: number;
}

