/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RideMetrics } from './rideMetrics';


export interface ActivityDetail { 
    id?: number;
    externalId?: string;
    name?: string;
    startTime?: string;
    ride?: RideMetrics;
}

