/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PowerZoneSettings } from './powerZoneSettings';
import { HrZoneSettings } from './hrZoneSettings';


export interface AppSettings { 
    aiProvider?: AppSettings.AiProviderEnum;
    aiModel?: string;
    powerZones?: PowerZoneSettings;
    hrZones?: HrZoneSettings;
}
export namespace AppSettings {
    export const AiProviderEnum = {
        Ollama: 'ollama',
        Anthropic: 'anthropic'
    } as const;
    export type AiProviderEnum = typeof AiProviderEnum[keyof typeof AiProviderEnum];
}


