/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarDayEntry } from './calendarDayEntry';


export interface CalendarResponse { 
    year?: number;
    month?: number;
    days?: Array<CalendarDayEntry>;
}

