/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalendarDayEntry { 
    date?: string;
    rideCount?: number;
    totalTss?: number;
    totalDistanceKm?: number;
    activityIds?: Array<number>;
}

