/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoachingRequest { 
    rideId: number;
    /**
     * Force re-generation even if coach_summary already exists
     */
    regenerate?: boolean;
}

