/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FtpEntry { 
    id?: number;
    date?: string;
    ftpValue?: number;
    testType?: FtpEntry.TestTypeEnum;
    notes?: string;
}
export namespace FtpEntry {
    export const TestTypeEnum = {
        AutoDetected: 'AUTO_DETECTED',
        Estimated: 'ESTIMATED'
    } as const;
    export type TestTypeEnum = typeof TestTypeEnum[keyof typeof TestTypeEnum];
}


