/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoalEvent { 
    id?: number;
    name?: string;
    eventDate?: string;
    eventType?: GoalEvent.EventTypeEnum;
    distanceKm?: number;
    elevationM?: number;
    notes?: string;
    status?: GoalEvent.StatusEnum;
}
export namespace GoalEvent {
    export const EventTypeEnum = {
        GranFondo: 'GRAN_FONDO',
        Race: 'RACE',
        Sportive: 'SPORTIVE'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
    export const StatusEnum = {
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


