/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoalEventRequest { 
    name: string;
    eventDate: string;
    eventType: GoalEventRequest.EventTypeEnum;
    distanceKm?: number;
    elevationM?: number;
    notes?: string;
}
export namespace GoalEventRequest {
    export const EventTypeEnum = {
        GranFondo: 'GRAN_FONDO',
        Race: 'RACE',
        Sportive: 'SPORTIVE'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


