/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HrZoneSettings { 
    /**
     * Zone 1 upper bound as % of max HR
     */
    z1Max?: number;
    /**
     * Zone 2 upper bound as % of max HR
     */
    z2Max?: number;
    /**
     * Zone 3 upper bound as % of max HR
     */
    z3Max?: number;
    /**
     * Zone 4 upper bound as % of max HR
     */
    z4Max?: number;
}

