/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NutritionPlan { 
    id?: number;
    rideId?: number;
    plannedWorkoutId?: number;
    /**
     * Target carbohydrate intake during ride in grams per hour
     */
    targetCarbsPerHourG?: number;
    /**
     * Target fluid intake during ride in ml per hour
     */
    targetFluidsMlPerHour?: number;
    /**
     * Pre-ride meal timing and composition guidance
     */
    preRide?: string;
    /**
     * During-ride nutrition strategy with product suggestions
     */
    duringRide?: string;
    /**
     * Post-ride recovery nutrition targets
     */
    postRide?: string;
    generatedAt?: string;
}

