/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkoutBlock } from './workoutBlock';


export interface PlannedWorkout { 
    id?: number;
    scheduledDate?: string;
    name?: string;
    workoutType?: PlannedWorkout.WorkoutTypeEnum;
    targetDurationSeconds?: number;
    targetTss?: number;
    workoutBlocks?: Array<WorkoutBlock>;
    completedRideId?: number;
}
export namespace PlannedWorkout {
    export const WorkoutTypeEnum = {
        Endurance: 'ENDURANCE',
        Intervals: 'INTERVALS',
        SweetSpot: 'SWEET_SPOT',
        Threshold: 'THRESHOLD',
        Recovery: 'RECOVERY',
        LongRide: 'LONG_RIDE'
    } as const;
    export type WorkoutTypeEnum = typeof WorkoutTypeEnum[keyof typeof WorkoutTypeEnum];
}


