/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PmcDataPoint { 
    date?: string;
    tss?: number;
    /**
     * Chronic Training Load — 42-day EWMA of TSS (fitness)
     */
    ctl?: number;
    /**
     * Acute Training Load — 7-day EWMA of TSS (fatigue)
     */
    atl?: number;
    /**
     * Training Stress Balance — CTL_yesterday minus ATL_yesterday (form)
     */
    tsb?: number;
}

