/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PowerZoneSettings { 
    /**
     * Zone 1 upper bound as % of FTP (Active Recovery)
     */
    z1Max?: number;
    /**
     * Zone 2 upper bound as % of FTP (Endurance)
     */
    z2Max?: number;
    /**
     * Zone 3 upper bound as % of FTP (Tempo)
     */
    z3Max?: number;
    /**
     * Zone 4 upper bound as % of FTP (Lactate Threshold)
     */
    z4Max?: number;
    /**
     * Zone 5 upper bound as % of FTP (VO2max)
     */
    z5Max?: number;
}

