/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RideMetrics { 
    distanceKm?: number;
    elevationGainM?: number;
    elevationDescentM?: number;
    durationSeconds?: number;
    avgPowerW?: number;
    maxPowerW?: number;
    avgHrBpm?: number;
    maxHrBpm?: number;
    avgCadenceRpm?: number;
    maxCadenceRpm?: number;
    normalizedPowerW?: number;
    intensityFactor?: number;
    tss?: number;
    ftpAtRide?: number;
    wattsPerKg?: number;
    bestPower5sW?: number;
    bestPower30sW?: number;
    bestPower1minW?: number;
    bestPower5minW?: number;
    bestPower10minW?: number;
    bestPower20minW?: number;
    bestPower60minW?: number;
    rpe?: number;
    coachSummary?: string;
    notes?: string;
}

