/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SyncStatus { 
    sessionValid?: boolean;
    lastSyncTime?: string;
    sessionExpiresAt?: string;
    message?: string;
}

