/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingWeek } from './trainingWeek';


export interface TrainingPlan { 
    id?: number;
    goalEventId?: number;
    generatedAt?: string;
    summary?: string;
    status?: TrainingPlan.StatusEnum;
    weeks?: Array<TrainingWeek>;
}
export namespace TrainingPlan {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Completed: 'COMPLETED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


