/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlannedWorkout } from './plannedWorkout';


export interface TrainingWeek { 
    id?: number;
    weekNumber?: number;
    startDate?: string;
    phase?: TrainingWeek.PhaseEnum;
    targetTss?: number;
    notes?: string;
    workouts?: Array<PlannedWorkout>;
}
export namespace TrainingWeek {
    export const PhaseEnum = {
        Base: 'BASE',
        Build: 'BUILD',
        Peak: 'PEAK',
        Taper: 'TAPER'
    } as const;
    export type PhaseEnum = typeof PhaseEnum[keyof typeof PhaseEnum];
}


