/**
 * Cycling Coach API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkoutBlock { 
    type?: WorkoutBlock.TypeEnum;
    durationSeconds?: number;
    /**
     * Lower bound power as % of FTP
     */
    powerLowPct?: number;
    /**
     * Upper bound power as % of FTP
     */
    powerHighPct?: number;
    repeat?: number;
}
export namespace WorkoutBlock {
    export const TypeEnum = {
        Warmup: 'WARMUP',
        SteadyState: 'STEADY_STATE',
        Intervals: 'INTERVALS',
        Cooldown: 'COOLDOWN',
        FreeRide: 'FREE_RIDE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


